# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='/RRR/mysite/blog/book_img'),
        ),
    ]
