# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161024_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='book_author',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='ordered',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='blog/static'),
        ),
    ]
