# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161106_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('book', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
    ]
